<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to Laminas MVC</h1>
</div>

<div class="row">
    <a href="<?=$this->url('image', ['action'=>'add'])?>" class="btn btn-primary">Add Image</a>
</div>

<table class="table table-hover">
    <thead>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
        <th scope="col">Action</th>
    </thead>
    <thead>
        <?php if (count($images) > 0): ?>
            <?php foreach($images as $image): ?>
                <tr>
                    <td><?=$image->getName()?></td>
                    <td><img src="http://192.168.0.19/<?=$image->getImage()?>" style="max-width: 200px;"></td>
                    <td>
                        <a href="<?=$this->url('image', ['action'=>'view', 'id'=>$image->getId()])?>" class="btn btn-primary">View</a>
                        <a href="<?=$this->url('image', ['action'=>'update', 'id'=>$image->getId()])?>" class="btn btn-success">Update</a>
                        <a href="<?=$this->url('image', ['action'=>'delete', 'id'=>$image->getId()])?>" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td>No record found!</td>
            </tr>
        <?php endif; ?>
    </thead>
</table>