<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<?php

$this->headLink()
    ->appendStylesheet($this->basePath("libs/ext-3.4.1/resources/css/ext-all.css"))
    ->appendStylesheet($this->basePath("libs/ext-3.4.1/examples/shared/examples.css"))
    ->appendStylesheet($this->basePath("libs/ext-3.4.1/examples/test/grid-examples.css"))
    ->appendStylesheet($this->basePath("libs/ext-3.4.1/examples/test/test.css"));

?>
<div>
    <h1>User Page   <a href="/">Return to Contact List</a> <a href="/login/logout">Logout</a></h1>
    <div id="form-example"></div>
    <br>
    <div id="grid-example"></div>
</div>

<?php $this->headScript()
    ->appendFile($this->basePath("libs/ext-3.4.1/adapter/ext/ext-base.js"))
    ->appendFile($this->basePath("libs/ext-3.4.1/ext-all.js"))
    ->appendFile($this->basePath("libs/ext-3.4.1/examples/test/user-form.js"))
?>
